import { Montserrat } from "next/font/google";
import "./globals.css";
import NavBar from "@/components/navbar/Navbar";

// Importing Montserrat from Google Fonts
const montserrat = Montserrat({
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  subsets: ["latin"],
  variable: "--font-montserrat",
});

export const metadata = {
  title: "Teen Alive Community",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${montserrat.variable} antialiased`}>
        <NavBar />
        {children}
      </body>
    </html>
  );
}
